### ISSUE TITLE
ClearChat

### ISSUE THREAD

**Issue by Shulkdown** [whereareiam/Socialismus#25]
[ENG] Add the /chatclear all and /chatclear commands
/ chatclear (permission: clearchat.personal) Clearing the chat for yourself.
/ chatclear all; nickname (chatclear.admin) Clearing the chat for all players/ player by nickname.

[RU] Добавить команду /chatclear all и /chatclear
/chatclear (permissiion: clearchat.personal) Очистка чата для себя.
/chatclear all; ник (chatclear.admin) Очистка чата у всех игроков/игрока по нику.

**Comment by whereareiam** [comment]
Implemented in https://github.com/whereareiam/Socialismus/commit/c55597aff7767d2dd97487f23ecce5cd815efa64
