### ISSUE TITLE
replacements

### ISSUE THREAD

**Issue by AllFiRE0** [whereareiam/Socialismus#31]
Chat message:
  [VIP] Player2004: Hello World!
⬇️⬇️⬇️⬇️⬇️⬇️⬇️⬇️⬇️⬇️⬇️⬇️⬇️⬇️⬇️⬇️⬇️⬇️⬇️
Config replacements
   prefix: 
     - &f This!
     - #FFFFFF hower!
     - &#FFFFFF message for VIP
    permission: replace.vip
    permission_error: null
 (This will disable the 
   hover if the player does
   not have the right) Or....
           permission_error:
             - &c Dude
             - &c you have 
             - &c no rights
    run_command:
      - open menu_prefix
    run_cmd:
      - command from console
    run_suggest:
      - hello %player_name%!
    sound_click: ??
⬇️⬇️⬇️⬇️⬇️⬇️⬇️⬇️⬇️⬇️⬇️⬇️⬇️⬇️⬇️⬇️⬇️⬇️⬇️  
 
 
Config chat message format
  {replace_prefix} %player_name%: {message}

⬇️⬇️⬇️⬇️⬇️⬇️⬇️⬇️⬇️⬇️⬇️⬇️⬇️⬇️⬇️⬇️⬇️⬇️⬇️

We receive the output of Hover messages on the player’s prefix and we can also output any Hover, a highly customizable Hover, anywhere and on anything in the chat!

Let it be a prefix, suffix, player nickname, or even the message itself, or even individual buttons created!!

With these functions, you can simply add a symbol 🌐
but if you add it to the chat format via %replace_symb_1% 
Then you can make a button out of this symbol, it will be able to display information about the time in the world, the type of chat, etc....

**Comment by whereareiam** [comment]
I don't understand how it should work, we already have swappers in Socialimus.
