### ISSUE TITLE
the %player_name% placeholder  on the head doesnt show correctly

### ISSUE THREAD

**Issue by steven11304** [whereareiam/Socialismus#4]
![圖片](https://github.com/whereareiam/Socialismus/assets/64590190/f8e4e284-0ecd-429e-a9a6-e376cbd5ad58)
the %player_name% placeholder  on the head doesnt show correctly

**Comment by whereareiam** [comment]
Hi, it's a placeholder from the PlaceholderAPI plugin. Have you installed PlaceholderAPI with the player extension?

**Comment by whereareiam** [comment]
I will close this issue due to inactivity, if the problem is still present then feel free to open another issue.
