### ISSUE TITLE
Problems with Protocollib

### ISSUE THREAD

**Issue by ghost** [whereareiam/Socialismus#5]
I'm using Paper 1.20.1 and ProtocolLib 5.1.0, the bubblechat and swapper functions don't work, I did a dump in protocollib and noticed that Socialismus doesn't use protocollib, I can't say for sure if the problem is in your plugin or in protocollib, but I decided to report it

**Comment by whereareiam** [comment]
Hi, are you using the paper version of the plugin for your setup? If so, can you set the debug mode to 2 and send the full log?

**Comment by ghost** [comment]
Yes, I use the paper version, log - https://mcpaste.io/6044f12d85e9fe0f

Additional information:
Protocol Version: ProtocolLib v5.1.0
Server Version: git-Paper-196 (MC: 1.20.1)
Java Version: 19.0.1

**Comment by whereareiam** [comment]
Can you send me a log where I can see that a player has joined and written a message in the chat?

**Comment by ghost** [comment]
Of course, log - https://mcpaste.io/bdfe3ee729272832

**Comment by whereareiam** [comment]
Are you sure that swapper and bubblechat are not working? As I can see in the log, it's working. Have you tried hitting F5 twice and then typing a message, a message should appear over your head.

**Comment by ghost** [comment]
Yes, I checked, and it didn't work, I did it -
I looked at the player through the second client and wrote to the chat.
I wrote in a chat with OP and without (and also different combinations, OP at all or all without OP).
Checked the permissions.
I looked at F5 also with and without the OP.
Disabled all other server plugins except placeholder api and protocollib.
(I apologize if something is unclear, I use a translator)

**Comment by whereareiam** [comment]
Can you send me your setup? I just need to see if it doesn't work.

**Comment by ghost** [comment]
I also noticed that when a player without an OP writes to the chat, an error appears in the console mentioning the second player standing next to him (the second player has an OP) "[ERROR]: [Socialismus] No bubble to remove for dsgd(the second client)" log - https://mcpaste.io/5287922c3ca67f47

Here are my plugin settings, I haven't changed much - [Config.zip](https://github.com/whereareiam/Socialismus/files/13189567/Config.zip)

**Comment by whereareiam** [comment]
I could reproduce the bug with bubblechat, looks like it's a problem in older version, I'll try to fix it, but for now you can use it with 1.20.2. Swapper suggestions works fine.

<img width="307" alt="image" src="https://github.com/whereareiam/Socialismus/assets/57540404/a699ca12-bc1f-44c5-8faf-cc1fe94b678d">

**Comment by ghost** [comment]
thank you so much for your support!
