### ISSUE TITLE
Thanks message spam

### ISSUE THREAD

**Issue by feliperobertosouz** [whereareiam/Socialismus#67]
## Checklist

Versions:
- Paper 1.21.1
- last version of placeholderAPI
- last version of protocolLib
- last version of socialismus (paper)

## Describe the bug
The message of thanks for using the plugin keeps being sent to each player

## To Reproduce
I installed the latest version of the plugin, started the server and joined as a player with op and as a regular player

## Expected behavior
Sending the message only the first time it was run or 1 time when signing in

## Screenshots
I don't have a screenshot now but it's about the message of aggression informing discord and social networks thanking for using the plugin

## Environment (please complete the following information):
 - Java: 21
 - Platform version: Paper 1.21.1 build 130
 - Module: socialismus  (paper)  with all default modules

**Comment by whereareiam** [comment]
Hi, thanks for your report, it's not a bug, it's a tempate for announcer which you can delete/disable or just disable the announcer module if you don't need it.
